const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),http=require('node:http');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const {createService}=require('../server/rooms.cjs');
const map=new Map();let rev=0;const copy=structuredClone;
const store={async read(k){return map.has(k)?copy(map.get(k)):null},async create(k,v){if(map.has(k))return false;map.set(k,{value:copy(v),etag:String(++rev)});return true},async write(k,v,etag){if(map.get(k)?.etag!==etag)return false;map.set(k,{value:copy(v),etag:String(++rev)});return true}};
let droppedReply=false;const service=createService(store),checks=[],errors=[],record=(s,ok)=>{assert.ok(ok,s);checks.push(s)};
const live=process.env.LIVE_URL;
(async()=>{const server=http.createServer((q,r)=>{r.setHeader('Content-Type','text/html');r.end(fs.readFileSync(path.join(__dirname,'../index.html')))});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=live||'http://127.0.0.1:'+server.address().port+'/';
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});
try{
 async function context(){const c=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});if(!live)await c.route('https://junyun-rooms.vercel.app/api/rooms',async route=>{const req=route.request();try{const out=await service(req.postDataJSON(),(req.headers().authorization||'').replace(/^Bearer /,''));if(req.postDataJSON().action==='submit'&&!droppedReply){droppedReply=true;await route.abort();return}await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(out)})}catch(e){await route.fulfill({status:e.status||500,contentType:'application/json',body:JSON.stringify({error:e.message})})}});c.on('response',async r=>{if(r.url().includes('/api/rooms')&&r.request().method()==='POST'){const action=r.request().postDataJSON()?.action;if(!r.ok()){let message='';try{message=(await r.json()).error||''}catch{}console.log(JSON.stringify({event:'api-error',action,status:r.status(),message}))}}});c.on('requestfailed',r=>{if(r.url().includes('/api/rooms'))console.log(JSON.stringify({event:'network-error',action:r.postDataJSON()?.action,error:r.failure()?.errorText}))});return c}
 const hc=await context(),host=await hc.newPage();host.on('pageerror',e=>errors.push(String(e)));await host.goto(base);await host.locator('#topic').fill('共享测试 · 三人奖金');for(let i=0;i<3;i++)await host.locator('[data-name="'+i+'"]').fill(['阿蓝','桃桃','薄荷'][i]);await host.locator('#setup button[type=submit]').click();await host.locator('[data-invite="0"]').waitFor();const invites=[];
 for(let i=0;i<3;i++){await host.locator('[data-invite="'+i+'"]').click();invites.push(await host.locator('#invite-link').inputValue());await host.locator('#close-invite-share').click()}
 record('invites share one room and distinct seats',new Set(invites.map(u=>u.split('#invite=')[1].split('.')[0])).size===1&&new Set(invites).size===3);await host.screenshot({path:path.join(__dirname,'v9-cloud-host.png'),fullPage:true});
 const pages=[];for(let i=0;i<3;i++){const c=await context(),p=await c.newPage();p.on('pageerror',e=>errors.push(String(e)));await p.goto(base+invites[i].slice(invites[i].indexOf('#')));await p.locator('#claim-invite').waitFor();record('seat '+i+' topic visible',(await p.locator('h1').innerText())==='共享测试 · 三人奖金');if(i===0)await p.screenshot({path:path.join(__dirname,'v9-cloud-invite.png'),fullPage:true});await p.locator('#claim-invite').click();await p.locator('#cloud-start').click();record('seat '+i+' all allocations visible',await p.locator('[data-push]').count()===3);record('seat '+i+' correct own identity',(await p.locator('.coin-seat.own .coin-person').innerText()).includes(['阿蓝','桃桃','薄荷'][i]));pages.push(p)}
 const dc=await context(),dup=await dc.newPage();await dup.goto(base+invites[0].slice(invites[0].indexOf('#')));await dup.locator('#claim-invite').waitFor();record('claimed invite refuses a second browser',!await dup.locator('#claim-invite').isEnabled());
 for(let i=0;i<3;i++){const p=pages[i];await p.locator('#amount-0').fill('400');await p.locator('#amount-1').fill('300');await p.locator('#amount-2').fill('300');await p.locator('#step-next').click();await p.locator('#tap-seal').click();if(i===0&&!live){await p.locator('.toast').waitFor();record('lost submit reply preserves editable proposal',await p.locator('#back').count()===1);await p.locator('#tap-seal').click()}await p.locator('#handoff-next').waitFor();record('seat '+i+' completion shows committed room progress',(await p.locator('.round-hud b').innerText()).includes((i+1)+' / 3'));await p.locator('#handoff-next').click();if(i<2){await p.locator('.room-progress').waitFor();record('results hidden after '+(i+1)+' submits',await p.locator('.result-player').count()===0)}}
 await pages[2].locator('.result-player').first().waitFor();await host.locator('#refresh-cloud').click();await host.locator('.result-player').first().waitFor();record('host cannot accept as participant',await host.locator('[data-accept]:enabled').count()===0);
 for(let i=0;i<3;i++){const p=pages[i];if(await p.locator('#refresh-cloud').count())await p.locator('#refresh-cloud').click();await p.locator('.result-player').first().waitFor();record('seat '+i+' can accept only own result',await p.locator('[data-accept]:enabled').count()===1&&await p.locator('[data-accept="'+i+'"]').isEnabled());await p.locator('[data-accept="'+i+'"]').click();await p.locator('[data-accept="'+i+'"][aria-pressed="true"]').waitFor();record('seat '+i+' acceptance is saved before continuing',true)}
 await pages[0].reload();await pages[0].locator('[data-recent]').click();await pages[0].locator('.result-player').first().waitFor();record('member session resumes after refresh',(await pages[0].locator('.consensus').innerText()).includes('3 / 3'));
 await pages[0].screenshot({path:path.join(__dirname,'v9-cloud-result.png'),fullPage:true});record('no runtime errors',errors.length===0);
 fs.writeFileSync(path.join(__dirname,live?'v9-cloud-live-report.json':'v9-cloud-browser-report.json'),JSON.stringify({mode:live?'live':'local service integration',checks,errors},null,2));console.log(JSON.stringify({checks:checks.length,errors}));
}catch(e){const states=[];for(const [i,c] of browser.contexts().entries())for(const [j,p] of c.pages().entries()){states.push({context:i,page:j,text:await p.locator('body').innerText()});await p.screenshot({path:path.join(__dirname,'cloud-failure-'+i+'-'+j+'.png'),fullPage:true})}fs.writeFileSync(path.join(__dirname,'cloud-failure-state.json'),JSON.stringify({checks,errors,states},null,2));throw e}finally{await browser.close();server.close()}})();
