const {test}=require('node:test'),assert=require('node:assert/strict'),{randomBytes}=require('node:crypto');
const {createService}=require('../server/rooms.cjs');
function memory(){const map=new Map();let rev=0;return {map,async read(k){await Promise.resolve();const v=map.get(k);return v?structuredClone(v):null},async create(k,v){if(map.has(k))return false;map.set(k,{value:structuredClone(v),etag:String(++rev)});return true},async write(k,v,e){if(map.get(k)?.etag!==e)return false;map.set(k,{value:structuredClone(v),etag:String(++rev)});return true}}}
const secret=()=>randomBytes(32).toString('base64url');
const spec={action:'create',topic:'周末比赛',config:{kind:'money',count:3,precision:2,label:'金钱',unit:'元'},total:10000,seats:['阿蓝','桃桃','薄荷']};
async function setup(){const store=memory(),api=createService(store),r=await api(spec),keys=r.seats.map(secret);await Promise.all(keys.map((member,seat)=>api({action:'claim',room:r.id,invite:r.invites[seat],seat,member})));return {store,api,r,keys}}
const submit=(r,shares=[4000,3000,3000])=>({action:'submit',room:r.id,ballot:{shares,tolerance:20}});
test('simultaneous participants preserve every ballot and reveal only final result',async()=>{const {api,r,keys,store}=await setup();const first=await api(submit(r),keys[0]);assert.equal(first.result,null);assert.equal(JSON.stringify(first).includes('shares'),false);const out=await Promise.all(keys.slice(1).map(k=>api(submit(r),k)));const final=await api({action:'status',room:r.id},r.credential);assert.deepEqual(final.result.amounts,[4000,3000,3000]);for(const denied of ['shares','tolerance','lower','upper','hostHash','memberHash','inviteHash','mean'])assert.equal(JSON.stringify(final).includes('"'+denied+'"'),false);assert.ok((await store.read('rooms/'+r.id+'.json')).value.players.every(p=>p.ballot));});
test('host, wrong token and other rooms cannot submit or read private proposals',async()=>{const {api,r,keys}=await setup();await assert.rejects(api(submit(r),r.credential),{status:403});await assert.rejects(api({action:'status',room:r.id},secret()),{status:403});const other=await api(spec);await assert.rejects(api({action:'status',room:other.id},keys[0]),{status:403});await assert.rejects(api({action:'status',room:r.id}),{status:403});});
test('racing invite claims have exactly one winner and same-browser retry is safe',async()=>{const api=createService(memory()),r=await api(spec);const [a,b]=[secret(),secret()];const claim=member=>({action:'claim',room:r.id,seat:0,invite:r.invites[0],member});const results=await Promise.allSettled([api(claim(a)),api(claim(b))]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);const winner=results[0].status==='fulfilled'?a:b;await api(claim(winner));await assert.rejects(api(claim(secret())),{status:409});});
test('submit is idempotent, sealed proposal immutable, acceptance is per-person and gated',async()=>{const {api,r,keys}=await setup();await api(submit(r),keys[0]);await api(submit(r),keys[0]);await assert.rejects(api(submit(r,[5000,3000,2000]),keys[0]),{status:409});await assert.rejects(api({action:'accept',room:r.id,accepted:true},keys[0]),{status:409});await Promise.all(keys.slice(1).map(k=>api(submit(r),k)));const s=await api({action:'accept',room:r.id,accepted:true,seat:2},keys[0]);assert.deepEqual(s.progress.map(p=>p.accepted),[true,false,false]);});
test('reject invalid totals, rows, tokens, oversized names and expired rooms',async()=>{const {api,r,keys,store}=await setup();await assert.rejects(api(submit(r,[10000,1,0]),keys[0]),{status:400});await assert.rejects(api({...spec,total:0}),{status:400});await assert.rejects(api({...spec,topic:'a'.repeat(41)}),{status:400});await assert.rejects(api({action:'claim',room:r.id,seat:8,invite:r.invites[0],member:secret()}),{status:403});const expired=createService(store,{now:()=>Date.now()+8*86400000});await assert.rejects(expired({action:'status',room:r.id},keys[0]),{status:410});});
test('global creation cap is atomic and fail closed',async()=>{const api=createService(memory());for(let i=0;i<30;i++)await api(spec);await assert.rejects(api(spec),{status:429});});
