const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const {install,TEST_ORIGIN}=require('./isolated-browser.cjs');
const report={sha256:require('node:crypto').createHash('sha256').update(fs.readFileSync(path.join(__dirname,'../index.html'))).digest('hex'),checks:[],screenshots:[],errors:[]};
const check=(name,pass)=>{assert.ok(pass,name);report.checks.push(name)};
const snap=async(p,name,fullPage=true)=>{const file='v9-controls-'+name+'.png';await p.screenshot({path:path.join(__dirname,file),fullPage,animations:'allow'});report.screenshots.push(file)};
(async()=>{const browser=install(await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH}));try{
const ctx=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const p=await ctx.newPage();p.on('pageerror',e=>report.errors.push(String(e)));
await p.goto(TEST_ORIGIN);await p.locator('[data-mode=local]').click();await p.waitForTimeout(420);await snap(p,'home');
await p.locator('#count-plus').scrollIntoViewIfNeeded();await p.evaluate(()=>{window.setupRef=document.querySelector('#setup');window.scrollBefore=scrollY});await p.locator('#count-plus').click();
check('count changes without replacing the form',await p.evaluate(()=>window.setupRef===document.querySelector('#setup')));check('count has immediate value and matching colored seats',await p.locator('#player-count').innerText()==='4'&&await p.locator('.party-dots i').count()===4);check('count keeps scroll position',await p.evaluate(()=>Math.abs(scrollY-window.scrollBefore)<2));await snap(p,'count-moving',false);await p.waitForTimeout(300);
await p.locator('[data-kind=percent]').click();check('resource selection restores keyboard focus',await p.locator('[data-kind=percent]').evaluate(e=>e===document.activeElement));check('one glass lens per selector',await p.locator('.control-lens').count()===2);await p.waitForTimeout(420);
check('selected lens aligns with percent choice',await p.evaluate(()=>{const a=document.querySelector('[data-kind=percent]').getBoundingClientRect(),b=document.querySelector('[data-lens=resource]').getBoundingClientRect();return Math.abs(a.x-b.x)<1&&Math.abs(a.width-b.width)<1}));
await p.locator('[data-kind=custom]').click();await p.locator('[data-kind=money]').click();await p.waitForTimeout(430);check('rapid selections settle at the final resource',await p.locator('[data-kind=money]').getAttribute('aria-pressed')==='true'&&await p.locator('#prize').inputValue()==='1000');
await p.locator('#topic').fill('周末比赛');await p.locator('[data-mode=cloud]').click();await p.locator('[data-name="0"]').fill('阿蓝');await p.locator('#count-plus').click();check('cloud names preserved after adding player',await p.locator('[data-name]').count()===5&&await p.locator('[data-name="0"]').inputValue()==='阿蓝');await p.locator('#count-minus').click();await p.locator('#count-minus').click();await p.locator('[data-mode=local]').click();
for(const width of [320,375,390,430,1440]){await p.setViewportSize({width,height:width===1440?1000:844});await p.waitForTimeout(420);check(width+' home fits',await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await snap(p,width+'-home');}
await p.setViewportSize({width:390,height:844});await p.waitForTimeout(400);await p.locator('.setup-card').screenshot({path:path.join(__dirname,'v9-controls-setup.png')});report.screenshots.push('v9-controls-setup.png');await p.locator('#setup button[type=submit]').scrollIntoViewIfNeeded();await p.waitForTimeout(250);const b=await p.locator('#setup button[type=submit]').boundingBox();await p.mouse.move(b.x+b.width/2,b.y+b.height/2);await p.mouse.down();await p.waitForTimeout(150);await snap(p,'primary-pressed',false);check('primary key visibly depresses',await p.locator('#setup button[type=submit]').evaluate(e=>new DOMMatrixReadOnly(getComputedStyle(e).transform).m42>1));await p.mouse.up();await p.locator('#next').waitFor();await p.waitForTimeout(400);await snap(p,'handoff');await p.locator('#next').click();await p.waitForTimeout(400);await snap(p,'table');await p.locator('#step-next').click();await p.waitForTimeout(400);await snap(p,'seal');
await p.locator('[data-tolerance="30"]').click();await p.waitForTimeout(430);check('tolerance lens aligns after selection',await p.evaluate(()=>{const a=document.querySelector('[data-tolerance="30"]').getBoundingClientRect(),b=document.querySelector('.glass-lens').getBoundingClientRect();return Math.abs(a.x-b.x)<1}));await p.locator('#tap-seal').click();await p.locator('#handoff-next').waitFor();await snap(p,'sealed');await p.reload();await p.locator('#resume').scrollIntoViewIfNeeded();await p.waitForTimeout(300);await snap(p,'resume',false);
const reduced=await browser.newContext({viewport:{width:375,height:667},reducedMotion:'reduce'});const r=await reduced.newPage();await r.goto(TEST_ORIGIN);await r.locator('#count-plus').click();check('reduced motion creates no number animation',await r.locator('#player-count').evaluate(e=>e.getAnimations().length===0));await r.locator('[data-mode=local]').click();check('reduced motion creates no selector animation',await r.locator('[data-lens]').evaluateAll(es=>es.every(e=>e.getAnimations().length===0)));await snap(r,'reduced-motion');
const media=await reduced.newCDPSession(r);await media.send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'},{name:'prefers-reduced-transparency',value:'reduce'}]});check('reduced transparency removes filters',await r.locator('.control-lens').first().evaluate(e=>getComputedStyle(e).backdropFilter)==='none');await snap(r,'solid');
check('zero page errors',report.errors.length===0);fs.writeFileSync(path.join(__dirname,'v9-controls-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({checks:report.checks.length,screenshots:report.screenshots.length,errors:report.errors}));
}catch(e){fs.writeFileSync(path.join(__dirname,'v9-controls-failure.json'),JSON.stringify({...report,failure:String(e)},null,2));throw e}finally{await browser.close()}})();
