const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const {install,TEST_ORIGIN}=require('./isolated-browser.cjs');
const dir=__dirname,url=process.env.TEST_URL||TEST_ORIGIN;
const report={sha256:require('node:crypto').createHash('sha256').update(fs.readFileSync(path.join(dir,'../index.html'))).digest('hex'),url,checks:[],errors:[],requests:[],screenshots:[]};
const check=(name,pass)=>{assert.ok(pass,name);report.checks.push(name)};
async function snap(p,name,active=false){await p.screenshot({path:path.join(dir,'v8-'+name+'.png'),fullPage:true,animations:active?'allow':'disabled'});report.screenshots.push('v8-'+name+'.png')}
async function fits(p,label){check(label,await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));check(label+' content',await p.locator('.coin-seat,.result-player,.setup-card').evaluateAll(es=>es.every(e=>e.scrollWidth<=e.clientWidth+1)))}
async function fresh(p){await p.goto(url);await p.evaluate(()=>localStorage.clear());await p.reload()}
async function start(p,{n=3,kind='money',total='100',label='资源',unit='份',precision=0}={}){
 await fresh(p);await p.locator('[data-mode=local]').click();if(kind!=='money')await p.locator('[data-kind="'+kind+'"]').click();
 if(kind==='custom'){await p.locator('#resource-label').fill(label);await p.locator('#resource-unit').fill(unit);if(precision)await p.locator('[data-precision="2"]').click()}
 if(kind!=='percent')await p.locator('#prize').fill(total);
 while(Number(await p.locator('#player-count').innerText())!==n)await p.locator(n>Number(await p.locator('#player-count').innerText())?'#count-plus':'#count-minus').click();
 await p.locator('#setup button[type=submit]').click();await p.locator('#next').click();
}
async function table(p,shares,name='测试'){await p.locator('#player-name').fill(name);for(let i=0;i<shares.length;i++)await p.locator('#amount-'+i).fill(String(shares[i]));}
async function seal(p,tolerance=20){await p.locator('#step-next').click();await p.locator('[data-tolerance="'+tolerance+'"]').click();await p.locator('#tap-seal').click();await p.locator('#handoff-next').waitFor()}
async function reveal(p){await p.locator('#next,#handoff-next').click();await p.locator('.result-player').first().waitFor()}
const amounts=async p=>(await p.locator('.result-amount strong').allTextContents()).map(x=>Number(x.replaceAll(',','')));
const rowValues=async p=>p.locator('[data-amount]').evaluateAll(es=>es.map(e=>Number(e.value)));
(async()=>{const browser=install(await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH}),url);try{
 const ctx=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce',acceptDownloads:true,offline:url.startsWith('file:')});const p=await ctx.newPage();
 p.on('pageerror',e=>report.errors.push(String(e)));p.on('console',m=>{if(m.type()==='error')report.errors.push(m.text())});p.on('request',r=>{if(!/^(file|data):/.test(r.url()))report.requests.push({url:r.url(),method:r.method(),type:r.resourceType()})});
 await fresh(p);await snap(p,'390-home');check('exactly money percentage custom',JSON.stringify(await p.locator('[data-kind] span').allTextContents())==='["金钱","百分比","自定义"]');check('new rounded-pencil mascot loaded',await p.locator('img').evaluateAll(es=>es.every(e=>e.complete&&e.naturalWidth>0)));await fits(p,'390 home');
 await p.locator('[data-kind=percent]').click();check('percentage total fixed at 100',await p.locator('#prize').inputValue()==='100'&&await p.locator('#prize').getAttribute('readonly')!==null);
 for(let i=0;i<15;i++)await p.locator('#count-plus').evaluate(e=>e.click());check('maximum count 12',await p.locator('#player-count').innerText()==='12');for(let i=0;i<15;i++)await p.locator('#count-minus').evaluate(e=>e.click());check('minimum count 2',await p.locator('#player-count').innerText()==='2');
 await start(p);check('coin layers overlap into horizontal stacks',await p.locator('.coin-stack').first().evaluate(e=>{const coins=[...e.children].map(c=>c.getBoundingClientRect());return coins.length>1&&coins.every(r=>r.width>r.height*1.6)&&coins[1].top<coins[0].top&&coins[1].bottom>coins[0].top}));check('everyone allocated simultaneously',await p.locator('[data-push]').count()===3&&await p.locator('[data-amount]').count()===3);check('three rows in phone viewport',await p.locator('.coin-seat').last().evaluate(e=>e.getBoundingClientRect().bottom<innerHeight));
 await p.locator('[data-nudge="0"][data-direction="1"]').click();check('plus adds one percent and redistributes peers',JSON.stringify(await rowValues(p))==='[34.34,32.83,32.83]');await p.locator('#equalize').click();await p.locator('#amount-0').fill('60');let v=await rowValues(p);check('fixed total moves peers together',v[0]===60&&v[1]+v[2]===40);check('larger share visibly has taller coin stacks',await p.locator('.coin-seat').evaluateAll(es=>{const height=e=>Math.max(...[...e.querySelectorAll('.coin-stack')].map(x=>x.getBoundingClientRect().height));return height(es[0])>height(es[1])}));await p.locator('#amount-0').fill('100');v=await rowValues(p);check('one participant can take full total',JSON.stringify(v)==='[100,0,0]');check('zero share has empty plates',await p.locator('[data-push="1"] .gold-coin,[data-push="2"] .gold-coin').count()===0);await p.locator('#amount-0').fill('40');check('zero peers recover equal shares',JSON.stringify(await rowValues(p))==='[40,30,30]');
 await p.locator('#player-name').fill('秘密阿蓝');await snap(p,'390-table');await p.locator('#cover').click();check('privacy curtain removes name and quantities',await p.locator('[data-amount]').count()===0&&!(await p.locator('#app').innerHTML()).includes('秘密阿蓝'));await p.locator('#uncover').click();check('private draft restored',await p.locator('#amount-0').inputValue()==='40');
 await p.locator('#amount-1').fill('999');await p.locator('#step-next').click();check('over total invalid submission blocked',await p.locator('[aria-invalid=true]').count()===1&&await p.locator('#step-next').count()===1);await p.locator('#equalize').click();await p.locator('#amount-0').fill('40');await p.locator('#step-next').click();await snap(p,'390-seal');check('range derived from own allocation',(await p.locator('#range-description').innerText()).includes('32 元'));await p.locator('#back').click();check('back retains all allocations',JSON.stringify(await rowValues(p))==='[40,30,30]');await p.locator('#step-next').click();
 // A wrong drop springs back, a valid drop seals once. Real pointer sequence.
 let c=await p.locator('#proposal-card').boundingBox();await p.mouse.move(c.x+c.width/2,c.y+c.height/2);await p.mouse.down();await p.mouse.move(c.x+25,c.y+30,{steps:8});await p.mouse.up();check('wrong drop does not submit',await p.locator('#seal-stage').getAttribute('data-state')==='idle');
 c=await p.locator('#proposal-card').boundingBox();let z=await p.locator('#drop-zone').boundingBox();await p.mouse.move(c.x+c.width/2,c.y+c.height/2);await p.mouse.down();await p.mouse.move(z.x+z.width/2,z.y+z.height/2,{steps:15});check('drop target reacts before release',await p.locator('#seal-stage').getAttribute('data-state')==='over');await snap(p,'390-drag-over');await p.mouse.up();await p.locator('#handoff-next').waitFor();check('completed turn removes private toolbar and gives prominent next action',await p.locator('.private-toolbar').count()===0&&(await p.locator('.seal-heading h1').innerText()).includes('轮到'));await snap(p,'390-sealed');check('commit persisted once',await p.evaluate(()=>JSON.parse(localStorage.getItem('junyun-v4-local')).ballots.length)===1);check('private values removed after sealing',await p.locator('#proposal-card,.range-control').count()===0);await p.locator('#handoff-next').click();check('direct next turn conceals sealed name',!(await p.locator('#app').innerHTML()).includes('秘密阿蓝'));
 await p.reload();check('refresh offers saved game',await p.locator('#resume').count()===1);await p.locator('#resume').click();check('resume preserves progress',(await p.locator('.eyebrow').innerText()).includes('1 / 3'));await p.locator('#next').click();check('next player starts with fresh draft',await p.locator('#player-name').inputValue()==='');await table(p,[40,30,30],'薄荷');await seal(p);await p.locator('#handoff-next').click();await table(p,[40,30,30],'桃桃');await seal(p);check('results gated until all complete and opening',await p.locator('.result-player').count()===0);await snap(p,'390-ready');await reveal(p);await snap(p,'390-result');check('shared identical plans remain 40 30 30',JSON.stringify(await amounts(p))==='[40,30,30]');
 await p.locator('[data-accept="2"]').scrollIntoViewIfNeeded();let y=await p.evaluate(()=>scrollY);await p.locator('[data-accept="2"]').click();check('accept keeps scroll',Math.abs(await p.evaluate(()=>scrollY)-y)<10);await p.locator('[data-accept="0"]').click();await p.locator('[data-accept="1"]').click();check('full onsite consensus',(await p.locator('.consensus').innerText()).includes('3 / 3'));await p.locator('[data-accept="1"]').click();check('acceptance retracts',(await p.locator('.consensus').innerText()).includes('2 / 3'));
 const d=p.waitForEvent('download');await p.locator('#save').click();await(await d).saveAs(path.join(dir,'v8-result.txt'));check('download has result but no full proposals',fs.readFileSync(path.join(dir,'v8-result.txt'),'utf8').includes('40 元'));
 await p.reload();await p.locator('#resume').click();check('results and acceptance resume',(await p.locator('.consensus').innerText()).includes('2 / 3'));
 for(const [width,height] of [[320,740],[375,667],[430,932],[1440,1000]]){await p.setViewportSize({width,height});await start(p);await snap(p,width+'-table');await fits(p,width+' table');if(width<500)check(width+' simultaneous three rows visible',await p.locator('.coin-seat').last().evaluate(e=>e.getBoundingClientRect().bottom<=innerHeight));if(width===375)check('375 continue button fits viewport',await p.locator('#step-next').evaluate(e=>e.getBoundingClientRect().bottom<=innerHeight));await p.locator('#step-next').click();await snap(p,width+'-seal');await fits(p,width+' seal');if(width<500)check(width+' seal button prominent and visible',await p.locator('#tap-seal').evaluate(e=>{const r=e.getBoundingClientRect();return r.height>=54&&r.width>innerWidth*.65&&r.bottom<=innerHeight+1}));await fresh(p);await snap(p,width+'-home');await fits(p,width+' home')}
 await p.setViewportSize({width:390,height:844});await start(p,{n:2,kind:'percent'});for(let i=0;i<2;i++){await table(p,[65,35],'份额'+i);await seal(p,0);if(i===0)await p.locator('#handoff-next').click()}await reveal(p);check('percentage case 65 35',JSON.stringify(await amounts(p))==='[65,35]');await snap(p,'percentage-result');
 for(const n of [6,12]){await start(p,{n,kind:'custom',total:'12',label:'值班轮次',unit:'次'});check(n+' all coin piles on same page',await p.locator('[data-push]').count()===n);await snap(p,n+'-table');check(n+' compact coin lanes',await p.locator('[data-push]').first().evaluate(e=>e.clientHeight===132));for(let i=0;i<n;i++){if(i===0){await p.locator('#step-next').click();await snap(p,n+'-seal');await fits(p,n+' seal');check(n+' proposal tabs fit inside ticket',await p.locator('#proposal-card').evaluate(e=>e.scrollWidth<=e.clientWidth+1));await p.locator('#back').click()}await seal(p,0);if(i<n-1)await p.locator('#handoff-next').click()}await reveal(p);check(n+' complete game total 12',(await amounts(p)).reduce((a,b)=>a+b,0)===12);await snap(p,n+'-result');await fits(p,n+' result')}
 await p.setViewportSize({width:320,height:740});await start(p,{n:2,total:'1000000'});await p.locator('#amount-0').fill('1000000');await p.locator('#player-name').fill('十六个汉字的名字也要完整地展示');await seal(p,0);await p.locator('#handoff-next').click();await p.locator('#amount-0').fill('1000000');await seal(p,0);await reveal(p);await snap(p,'max-money');await fits(p,'max money');check('maximum amount preserved',JSON.stringify(await amounts(p))==='[1000000,0]');
 await start(p,{n:2,kind:'custom',total:'0.01',label:'<script>份额',unit:'<b>',precision:2});for(let i=0;i<2;i++){await p.locator('#player-name').fill('<img>名字');await seal(p,0);if(i===0)await p.locator('#handoff-next').click()}await reveal(p);check('smallest custom unit preserved',JSON.stringify(await amounts(p))==='[0.01,0]');check('user content escaped',await p.locator('.result-person img,#app script').count()===0&&(await p.locator('.result-person h2').first().innerText()).includes('<img>'));
 await start(p,{kind:'custom',total:'100'});for(let i=0;i<3;i++){await p.locator('#amount-'+i).fill('60');await seal(p,10);if(i<2)await p.locator('#handoff-next').click()}await reveal(p);check('incompatible ranges clearly show shortage 62',(await p.locator('.conflict').innerText()).includes('62 份'));await snap(p,'conflict');
 await p.locator('#renegotiate').click();await p.locator('#cancel-reset').click();check('cancel renegotiation keeps completed proposals',await p.locator('.result-player').count()===3&&await p.evaluate(()=>JSON.parse(localStorage.getItem('junyun-v4-local')).ballots.length)===3);
 await p.locator('#renegotiate').click();await p.locator('#confirm-reset').click();check('new round preserves resource and clears previous ballots',await p.evaluate(()=>{const s=JSON.parse(localStorage.getItem('junyun-v4-local'));return s.ballots.length===0&&s.total===100&&s.config.unit==='份'}));await p.locator('#next').click();check('new round starts from balanced allocation',JSON.stringify(await rowValues(p))==='[34,33,33]');for(let i=0;i<3;i++){await seal(p,0);if(i<2)await p.locator('#handoff-next').click()}await reveal(p);check('second round reaches a feasible result',await p.locator('.conflict').count()===0&&JSON.stringify(await amounts(p))==='[34,33,33]');await snap(p,'renegotiated');
 await p.locator('#reset-btn').click();await p.locator('#cancel-reset').click();check('cancel reset preserves results',await p.locator('.result-player').count()===3);await p.locator('#reset-btn').click();await p.locator('#confirm-reset').click();check('reset removes saved round',await p.locator('#resume').count()===0&&await p.evaluate(()=>localStorage.getItem('junyun-v4-local')===null));
 await start(p);await p.locator('#player-name').fill('未封存秘密');await p.reload();await p.locator('#resume').click();await p.locator('#next').click();check('unsaved private draft not restored',await p.locator('#player-name').inputValue()==='');await p.locator('#step-next').click();await p.locator('#proposal-card').focus();await p.keyboard.press('Enter');await p.locator('#handoff-next').waitFor();check('keyboard seal path works',await p.evaluate(()=>JSON.parse(localStorage.getItem('junyun-v4-local')).ballots.length)===1);
 await p.locator('#handoff-next').click();await p.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true})));check('back-forward restore removes private draft',await p.locator('[data-push]').count()===0);await p.locator('#resume').click();await p.locator('#next').click();{const a=await p.locator('[data-push="0"]').boundingBox(),b=await p.locator('[data-push="2"]').boundingBox();await p.mouse.move(a.x+a.width/2,a.y+a.height/2);await p.mouse.down();await p.mouse.move(b.x+b.width/2,b.y+b.height/2,{steps:4});check('coin push is active before privacy curtain',await p.locator('.pushing').count()===1)}await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'))});check('privacy curtain removes active slider and amounts',await p.locator('[data-push],.pushing,[data-amount]').count()===0);await p.mouse.up();check('background change covers draft',await p.locator('#uncover').count()===1);check('reduced motion stops decorative entry',await p.locator('.screen').evaluate(e=>getComputedStyle(e).animationName)==='none');
 // Normal motion + real emulated touch drag, inspect intermediate phases.
 const touch=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,offline:url.startsWith('file:')});const t=await touch.newPage();t.on('pageerror',e=>report.errors.push(String(e)));await start(t);await t.waitForTimeout(400);let cp0=await t.locator('[data-push="0"]').boundingBox();const coinCDP=await touch.newCDPSession(t),pushX=cp0.x+cp0.width/2,pushY=cp0.y+cp0.height*.65;
 await coinCDP.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:pushX,y:pushY}]});
 for(let k=1;k<=8;k++)await coinCDP.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:pushX,y:pushY-k*5}]});
 await t.evaluate(()=>new Promise(requestAnimationFrame));let moving=await rowValues(t);check('real touch continuously increases selected share',moving[0]>50&&moving[1]<33.33&&moving[2]<33.33);check('push preserves exact total during gesture',Math.round(moving.reduce((a,b)=>a+b,0)*100)===10000);check('active coin column and grip visible',await t.locator('.pushing').count()===1);await snap(t,'push-active',true);
 await coinCDP.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});check('release retains allocation and clears active state',JSON.stringify(await rowValues(t))===JSON.stringify(moving)&&await t.locator('.pushing').count()===0);
 await table(t,[43.21,36.54,20.25]);const beforeReverse=await rowValues(t);cp0=await t.locator('[data-push="0"]').boundingBox();const rx=cp0.x+20,ry=cp0.y+100;await coinCDP.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:rx,y:ry}]});for(const dy of [-40,-20,0])await coinCDP.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:rx,y:ry+dy}]});await coinCDP.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});check('reversing a push restores asymmetric peers without rounding drift',JSON.stringify(await rowValues(t))===JSON.stringify(beforeReverse));
 await t.locator('#equalize').click();cp0=await t.locator('[data-push="0"]').boundingBox();await coinCDP.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:cp0.x+20,y:cp0.y+90}]});await coinCDP.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:cp0.x+20,y:cp0.y+45}]});await coinCDP.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});check('canceled touch restores complete original allocation',JSON.stringify(await rowValues(t))==='[33.34,33.33,33.33]');
 await t.locator('[data-push="0"]').focus();await t.keyboard.press('End');check('slider keyboard end gives full amount',JSON.stringify(await rowValues(t))==='[100,0,0]');await t.keyboard.press('Home');check('slider keyboard home redistributes evenly',JSON.stringify(await rowValues(t))==='[0,50,50]');await t.locator('#equalize').click();
 await t.locator('#step-next').click();await t.waitForTimeout(400);const cd=await touch.newCDPSession(t);c=await t.locator('#proposal-card').boundingBox();z=await t.locator('#drop-zone').boundingBox();const x=c.x+c.width/2,endX=z.x+z.width/2,startY=c.y+c.height/2,endY=z.y+z.height/2;await cd.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y:startY}]});for(let k=1;k<=10;k++)await cd.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+(endX-x)*k/10,y:startY+(endY-startY)*k/10}]});check('touch drag highlights target',await t.locator('#seal-stage').getAttribute('data-state')==='over');await snap(t,'touch-over',true);await cd.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});check('real motion starts swallow',await t.locator('#seal-stage').getAttribute('data-state')==='swallow');await t.waitForTimeout(160);await snap(t,'swallow-motion',true);await t.waitForTimeout(570);check('lid closes and lock appears',await t.locator('#seal-stage').getAttribute('data-state')==='closed');await snap(t,'closed-motion',true);await t.locator('#handoff-next').waitFor();await snap(t,'sealed-motion');check('single touch commit',await t.evaluate(()=>JSON.parse(localStorage.getItem('junyun-v4-local')).ballots.length)===1);
 await t.locator('#handoff-next').click();await t.locator('#step-next').click();await t.locator('#tap-seal').evaluate(e=>{e.click();e.click()});await t.locator('#handoff-next').waitFor();check('double click does not duplicate commit',await t.evaluate(()=>JSON.parse(localStorage.getItem('junyun-v4-local')).ballots.length)===2);
 // Persistence denial and corrupted data are user-visible without breaking local play.
 const denied=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});await denied.addInitScript(()=>{Storage.prototype.setItem=function(){throw new DOMException('Blocked','SecurityError')}});const dp=await denied.newPage();await dp.goto(url);await dp.locator('[data-mode=local]').click();await dp.locator('#setup button[type=submit]').click();check('storage denial shown before private turn',(await dp.locator('.handoff-card').innerText()).includes('本局暂未保存'));await dp.locator('#next').click();await dp.locator('#step-next').click();await dp.locator('#tap-seal').click();await dp.locator('#handoff-next').waitFor();check('storage failure never claims saved',(await dp.locator('.seal-heading p').innerText()).includes('未允许保存'));
 await fresh(t);await t.evaluate(()=>localStorage.setItem('junyun-v4-local','{broken'));await t.reload();check('corrupt storage safely ignored',await t.locator('#setup').count()===1&&await t.locator('#resume').count()===0);
 await start(t);await t.locator('#step-next').click();await t.locator('#tap-seal').click();await t.reload();await t.locator('#resume').click();check('refresh during animation retains exactly one ballot',(await t.locator('.eyebrow').innerText()).includes('1 / 3'));
 check('no browser errors',report.errors.length===0);check('no input uploads or external assets',report.requests.every(r=>r.method==='GET'&&r.type==='document'&&r.url===url));
 fs.writeFileSync(path.join(dir,'v8-browser-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({checks:report.checks.length,screenshots:report.screenshots.length,errors:report.errors}));
}catch(e){fs.writeFileSync(path.join(dir,'v8-failure.json'),JSON.stringify({...report,failure:String(e)},null,2));throw e}finally{await browser.close()}})();
